from typing import Iterator, Protocol


class Trie[K](Protocol):
    def __getitem__(self, key: K, /) -> "Trie[K]": ...

    def __contains__(self, key: K, /) -> bool: ...

    def __iter__(self) -> Iterator[tuple[K, "Trie[K]"]]: ...

    @property
    def keys(self) -> Iterator[K]: ...

    @property
    def count(self) -> int: ...
